
services:
  web:
    build:
      context: .
      dockerfile: TactiX/Dockerfile
    volumes:
      - ./:/app:delegated
    ports:
      - "5000:80"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - ConnectionStrings__TactiXDB=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
  
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: